name: Amazon UI CI/CD

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Building Amazon UI"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: |
          if grep -q "Amazon" index.html; then
            echo "TEST PASSED"
          else
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploy successful"